kind: pipeline
type: docker
name: Linting

platform:
  os: linux
  arch: arm64

trigger:
  event:
    include:
      - push

steps:
  - name: Prettier
    image: node:alpine
    commands:
      - apk add musl-dev sqlite sqlite-dev python2 gcc make
      - yarn install
      - yarn prettier --check src/**/*.js
