kind: pipeline
type: docker
name: Linting

platform:
  os: linux
  arch: arm64

steps:
  - name: Prettier
    image: node:latest
    commands:
      - yarn install
      - yarn prettier --check src/**/*.js
